<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SHOUT IT!</title>
    <link href="public/style.css" rel="stylesheet">
</head>
<body>
     <div id="container">
     <header>
     <h1>SHOUT IT! Shoutbox</h1>
     </header>
    <div id="shouts">
        <ul>
        <?php foreach ($shouts as $shout) : ?>
            <li class="shout"><span><?= $shout['time'] ?> - </span><strong><?= $shout['user'] ?>:</strong> <?= $shout['message'] ?></li>
        <?php endforeach; ?>
        </ul>
     </div>
     <div id="input">
     <?php if(isset($query['error'])) :?>
     <div class="error"><?= $query['error']?></div>
     <?php endif; ?>
     <form action="/create-shout" method="POST">
        <input type="text" name="user" placeholder="Enter Your Name">
        <input type="text" name="message" placeholder="Enter a Message">
        <input type="submit" value="Shout It Out" class="shout-btn" >
    </form>
     </div>
    </div>
</body>
</html>